// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdD6hP43jfI8qWxx4viUttOlGCtNBtmRo',
    appId: '1:702932527035:web:494b3029128a85c3ef869e',
    messagingSenderId: '702932527035',
    projectId: 'kookoo-e8422',
    authDomain: 'kookoo-e8422.firebaseapp.com',
    storageBucket: 'kookoo-e8422.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEhFCN3vz7ISHOc713W6hqI3ho1UVjKBA',
    appId: '1:702932527035:android:c911afbca6a659beef869e',
    messagingSenderId: '702932527035',
    projectId: 'kookoo-e8422',
    storageBucket: 'kookoo-e8422.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTirDs-lOtQRZ4N-X5Fl27DGw-FqupazM',
    appId: '1:702932527035:ios:8a0ba592cd0e4766ef869e',
    messagingSenderId: '702932527035',
    projectId: 'kookoo-e8422',
    storageBucket: 'kookoo-e8422.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTirDs-lOtQRZ4N-X5Fl27DGw-FqupazM',
    appId: '1:702932527035:ios:8a0ba592cd0e4766ef869e',
    messagingSenderId: '702932527035',
    projectId: 'kookoo-e8422',
    storageBucket: 'kookoo-e8422.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdD6hP43jfI8qWxx4viUttOlGCtNBtmRo',
    appId: '1:702932527035:web:04689e6e3d9035feef869e',
    messagingSenderId: '702932527035',
    projectId: 'kookoo-e8422',
    authDomain: 'kookoo-e8422.firebaseapp.com',
    storageBucket: 'kookoo-e8422.firebasestorage.app',
  );
}
